# Generated by Django 4.2.1 on 2023-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('tools', models.CharField(max_length=1000)),
                ('goal', models.CharField(max_length=1000)),
                ('link_to_site', models.CharField(max_length=500)),
                ('link_to_code', models.CharField(max_length=500)),
            ],
        ),
    ]
