# Generated by Django 4.2.1 on 2023-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('title', 'title'), ('progress_bar', 'progress_bar'), ('text', 'text')])),
                ('skill', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
