# Generated by Django 4.2.1 on 2023-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('title', 'title'), ('progress_bar', 'progress_bar'), ('text', 'text')])),
                ('text', models.CharField(max_length=200)),
                ('skill_score', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
