# Generated by Django 4.2.1 on 2023-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skill_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_score',
            field=models.PositiveIntegerField(blank=True, default=123),
            preserve_default=False,
        ),
    ]
