# Generated by Django 4.2.1 on 2023-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_skill_options_skill_is_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['short_title']},
        ),
        migrations.AddField(
            model_name='skill',
            name='to_improve',
            field=models.BooleanField(default=False),
        ),
    ]
